  - name: restart-vsftpd
    # sudo systemctl restart vsftpd
    # sudo systemctl enable vsftpd
    listen: "restart vsftpd"
    service:
      name: vsftpd
      state: reloaded
      enabled: yes
    become: yes